- hosts: master
  become: true
  tasks:
    - name: Ensure kubeconfig exists
      stat:
        path: /home/ubuntu/.kube/config
      register: kubeconfig_file

    - name: Fail if kubeconfig missing
      fail:
        msg: "Kubeconfig file is missing! Ensure cluster is initialized."
      when: not kubeconfig_file.stat.exists

    - name: Apply deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yaml
